name: Scheduled Job

on:
  schedule:
    - cron: '0 10 * * *'
    - cron: '0 19 * * *'
  workflow_dispatch:

jobs:
  run-cron-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Your Script
        run: |
          echo "Running scheduled task..."
          # Add your script or command here
