name: Scheduled Trigger - MAIN

on:
  schedule:
    - cron: '*/2 * * * *'  # Runs every 2 minutes

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Print Job Status
        run: echo "JOB is working"
