name: Scheduled Trigger - Primary

on:
  schedule:
    - cron: '*/1 * * * *'
jobs:
  run-script:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Print Time
        run: echo "Workflow triggered at $(date)"
